config/routes.rb
Rails.application.routes.draw do
  
  
  #resources :interventions
  get 'speak/watson'
  get 'speak/star_wars'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  get '/form',                  to: 'pages#form'
  get '/residential',           to: 'pages#residential'
  get '/commercial',            to: 'pages#commercial'
  get '/google',                to: 'google#index'
  get '/quote_confirm',         to: 'pages#quote_confirm'
  get '/terms_and_conditions',  to: 'pages#terms_and_conditions'
  get '/interventions',          to: 'intervention#new'
  # get '/intervention', to: 'intervention#index'

  #get '/leads', to: 'leads#create'
 

  get 'home/index'
  
  resources :quotes
  resources :employees
  resources :leads

  # get '/WatsonSpeaker/watson'

  # Rails.application.routes.draw do
  resources :interventions
    get 'get_buildings'   => 'interventions#get_buildings'
    get 'get_batteries'   => 'interventions#get_batteries'
    get 'get_columns'     => 'interventions#get_columns'
    get 'get_elevators'   => 'interventions#get_elevators'
    post '/interventions', to: 'interventions#create'

  # get 'speak/watson'
  #   devise_for :users, controllers: {
  #     sessions: 'users/sessions'
  #   }
  # end

end

app/models/intervention.rb
require './lib/API/zendesk.rb'

class Intervention < ApplicationRecord
    # after_create :intervention

    belongs_to :customer,   optional: true
    belongs_to :building,   optional: true
    belongs_to :battery,    optional: true
    belongs_to :column,     optional: true
    belongs_to :elevator,   optional: true 
    belongs_to :employee,   optional: true

    
def intervention

    zendesk = Zendesk.new

    zendesk.intervention(self.author, self.customer_id, self.building_id, self.battery_id, self.column_id, self.elevator_id, self.employee_id, self.report )
end
    
end

app/controllers/interventions_controller.rb
require './lib/API/zendesk.rb'
class InterventionsController < ApplicationController

  #before_action :set_intervention, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :js, :json, :html
  

  # GET /interventions
  # GET /interventions.json
  def index
    @intervention = Intervention.all
  end


  # serge exemple 

  # def getBuildingsForCustomer
  #   puts "getBuildingsForCustomer"
  #   puts params
  #   customer_id = params[:customer_id]
  #   buildings = Building.where(customer_id: customer_id)
  #   render json: buildings
  # end

    def new       
      @intervention = Intervention.new
      logger.info("INTERVENTIONS CONTROLLER ")        
    end

    def get_buildings
      customer_id = params[:customer_id]
      buildings = Building.where(customer_id: customer_id)
      render json: buildings
    end
    
    def get_batteries
      building_id = params[:building_id]
      batteries= Battery.where(building_id: building_id)
      render json: batteries
    end
    # def get_buildings
    #     building_id = params[:building_id]
    #     batteries = Battery.where(building_id: building_id)
    #     render json: batteries
    # end
 
    def get_columns
      battery_id = params[:battery_id]
      columns = Column.where(battery_id: battery_id)
      render json: columns
    end

    def get_elevators
      column_id = params[:column_id]
      elevators = Elevator.where(column_id: column_id)
      render json: elevators
    end
    


   

    
    
    
    # GET /interventions/1
    # GET /interventions/1.json
    def show
    end
    
    # GET /interventions/new
    def new
      @intervention = Intervention.new
    end
    
    # GET /interventions/1/edit
    def edit
    end
    
    # POST /interventions
    # POST /interventions.json
    def create
      
    @intervention = Intervention.new
    
  
   
    author            = current_user.id
    customer_id       = params['customer_id']
    building_id       = params['building_id']
    battery_id        = params['battery_id']
    column_id         = params['column_id']
    elevator_id       = params['elevator_id']
    employee_id       = params['Employee_name']
    description       = params['Message']
    
    @intervention = Intervention.new
  
      @intervention.author        = current_user.id
      @intervention.customer_id   = customer_id
      @intervention.building_id   = building_id
      @intervention.battery_id    = battery_id
      @intervention.column_id     = column_id
      @intervention.elevator_id   = elevator_id
      @intervention.employee_id   = employee_id
      @intervention.report        = description
      @intervention.save!
      
      @intervention.intervention
      redirect_to quote_confirm_path
      

    end
  
  # PATCH/PUT /interventions/1
  # PATCH/PUT /interventions/1.json
    def update
      respond_to do |format|
        if @intervention.update(intervention_params)
          format.html { redirect_to @intervention, notice: 'Intervention was successfully updated.' }
          format.json { render :show, status: :ok, location: @intervention }
        else
          format.html { render :edit }
          format.json { render json: @intervention.errors, status: :unprocessable_entity }
        end
      end
    end
  
  # DELETE /interventions/1
  # DELETE /interventions/1.json
    def destroy
      @intervention.destroy
      respond_to do |format|
        format.html { redirect_to interventions_url, notice: 'Intervention was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def intervention_params
      params.fetch(:intervention, {})
    end
  
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(url: interventions_path(), local: true) do |form| %>

<section class="page-header quoteHeaderColor">
                <div class="container">           
                    <!-- breadcrumbs -->
                  <ol class="breadcrumb">
                        <li><a href="/" style="color:white">Home</a></li>
                        <li class="active">Rocket</li>
                    </ol><!-- /breadcrumbs -->            
                </div>

                <div class="form-group col-md-4 container mt-2" align="center" >

				        <label for="author">Ticket Author :</label>

                <input id="" class="center" name="author_ticket" type="" value="<%= current_user.employee.first_name + " " + current_user.employee.last_name  %>" style="padding: 16px; border-radius: 15px;" disabled/>
			
			          <input id="" class="center" name="author_" type="hidden" value="<%= current_user.employee.first_name + current_user.employee.last_name  %>"/>
                </div>

              <div class="form-group col-md-4 container mt-2" align="center" >
                <div class= "chooseType">
                  <label class= "labelStyle">Employees</label>
                  <select class= "ansStyle" onchange="showHide()" id= "Employee_Name" name="Employee_name">
                    <option value="">--Choose Employee--</option>
                    <% Employee.all.each do |c|%>
                      <option value="<%= c.id %>"><%= c.first_name %> <%= c.last_name %>  id: <%= c.id %></option>
                    <% end %>
                    <input id="c" class="center" name="author" type="hidden"/>
                  </select>
                </div>
              </div>
                   
                </section>


                <div class= "chooseType">
                  <label class= "labelStyle">Costomer Name</label>
                  <select class= "ansStyle" onchange="customer()" id="customer_id" name="customer_id">   
                  <option value="">--Choose Costumer--</option>                 
                    <% Customer.all.each do |c|%>
                      <option value="<%= c.id %>"><%= c.full_name %></option>
                    <% end %>
                  </select>
                </div> 



                <div class= "chooseType">
                  <label class= "labelStyle">building</label>
                  <select class= "ansStyle" onchange="building()" id= "building_id" name="building_id">
                    <option value="">--Choose Building--</option>                      
                    <% Building.all.each do |c|%>
                      <option value="<%=c.id %>"><%= c.id%></option>
                    <% end %>
                  </select>
                </div>



                <div class= "chooseType">
                  <label class= "labelStyle">Choose Battery</label>
                    <select class= "ansStyle" onchange="battery()" id= "battery_id" name="battery_id">
                    <option value="">--Choose Battery--</option>
                    <% Battery.all.each do |c|%>
                      <option value="<%=c.id %>"><%= c.id%></option>
                    <% end %>
                  </select>
                </div>



                <div class= "chooseType">
                  <label class= "labelStyle">Choose Column</label>
                    <select class= "ansStyle" onchange="column()" id= "column_id" name="column_id">
                      <option value="">--Choose column--</option>
                      <% Column.all.each do |c|%>
                        <option value="<%= c.id %>"><%= c.id%></option>
                      <% end %>
                    </select>
                </div>


                        
                <div class= "chooseType">
                  <label class= "labelStyle">Choose Elevator</label>
                    <select class="ansStyle" onchange="elevator()" id= "elevator_id" name="elevator_id">
                      <option value="">--Choose elevator--</option>
                      <% Elevator.all.each do |c|%>
                        <option value="<%= c.id %>"><%= c.id%></option>
                      <% end %>
                    </select>
                </div>



                <div class= "divSize"> 
                  <div class= "askStyle">
                    <label class= "labelStyle">Desciption of the intervention</label>
                    <div class= "quoteStyle">                                     
                    <div class="col-md-12">
                    <label for="contact:message">Message *</label>
                    <textarea required maxlength="10000" rows="4" class="form-control" name="Message" id="contact:message"></textarea>
                </div>
              </div>
            </div>      
          </div>
                  <%# <%= form_with(model: @intervention, local: true) do |form|                                                                                                        
                  <% if intervention.errors.any? %>
  <div class="actions">
    <button class="btn btn-red btn-lg" style="margin-top: 15px;" type= 'submit' >Submit</button>
  </div>
                                                                    

</form>
<% end %>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
    <% end %>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<h1>New Intervention</h1>
<%= render 'form', intervention: @intervention %>

<%= link_to 'Back', root_path %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', quote_confirm_path %>